name: Pets
main: me.pets.core.PetsPlugin
version: 1.0.0
api-version: 1.20
commands:
  pets:
    description: Pets user command
    usage: /pets
  pet:
    description: Pet abilities and admin tools
    usage: /pet
  givepetrandom:
    description: Give a random pet to a player
    usage: /givepetrandom <player>
permissions:
  pets.admin:
    description: Allows granting and random pet commands
    default: op
